---
title: Ressources
---

# Livres
- Wickham, H., & Grolemund, G. (2016). *[R for Data Science: import, tidy, transform, visualize, and model data](http://r4ds.had.co.nz/)*. O'Reilly Media, Inc.

# Cheatsheets

- [R Studio](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf)
- [R Markdown](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)
- [Traitement](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)
- [Visualisation](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf)

# Logiciels
- [R](https://www.r-project.org/) est un langage de programmation en accès libre principalement utilisé pour les statistiques et l'analyse de données.
- [RStudio](https://www.rstudio.com/) est une logiciel de développement gratuit et facile à utiliser pour programmer en R ou d'autres langues.
- [git](https://git-scm.com/) est un système de contrôle de version en accès libre qui vous permet de garder des traces des changements effectués dans vos fichiers.

# Tutoriels
- [Markdown](https://commonmark.org/help/tutorial/)

# Divers

## Écriture

- 1 page = ~ 5 paragraphes
- 1 paragraphe =  ~ 5 phrases
- 1 phrase = ~ 20 mots

De même 1 paragraphe = 1 idée = 5 phrases.

- La première phrase introduit l'idée
- Suivi de trois points/arguments que l'on souhaite mettre en avant
- La dernière phrase conclu l'idée

## Références et bibliographie
- Style à utiliser : [Guide APA](https://www.mendeley.com/guides/apa-citation-guide)

